### PR TITLE
Added an example to the usage

### PR DESCRIPTION
**Pull request by jamtur01**
Expanded the Usage example to make the workflow a bit clearer.

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
Hi @jamtur01, thanks for the PR! The example is now much easier to understand!

Just some style nitpicks:

* I recently added a markdown linter to keep a consistent style in the markdown files too. Could you check the build and fix the style issues?
* Could you use `shell` instead of `Shell` and `ruby` instead of `Ruby` in the code blocks?
* Could you use `bin/rails` instead of `rails` in the example?

Thanks!

**Comment by jamtur01** [comment]
Think that should fix it up. Can squash if you'd prefer too.

**Comment by deivid-rodriguez** [comment]
Yes, please! :)

**Comment by jamtur01** [comment]
Done!

**Comment by deivid-rodriguez** [comment]
Thanks!

**Pull request merged**
