### PR TITLE
Fix issue 197 by clearing and restoring ARGV

### PR DESCRIPTION
**Pull request by josephks**
See #197 

Test results are the same on this branch as on master.

I tested manually with https://github.com/josephks/bug_demo and this fix works.  I'm not sure how to write an automated test for this.

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
Yep, it's not easy to write an automated test for this. I think we can live without it!

Can you change the code to look like this:

```ruby
with_clean_argv { IRB.start(__FILE__) }
```

and move all the ARGV handling logic to a separate `with_clean_argv` private method?

**Comment by josephks** [comment]
Updated

**Comment by deivid-rodriguez** [comment]
@josephks Just one more nitpick and I'm happy to merge. Now that this is extracted into a method, you no longer need the explicit `begin`, the beginning of the method does the same job. Could you remove it?

Thanks! :)

**Comment by josephks** [comment]
:question: I don't have a begin at the beginning of the method.

**Comment by deivid-rodriguez** [comment]
Oh sorry, I mean like this

```ruby
def with_clean_argv
  saved_argv = ARGV.dup
  ARGV.clear
  yield
ensure
  ARGV.concat(saved_argv)
end
```

**Comment by josephks** [comment]
I didn't do that on purpose.  I only want to restore ARGV after it has been cleared.  If somehow something went wrong with the dup or the clear then I don't want to restore.

**Comment by deivid-rodriguez** [comment]
I think if `ARGV.dup` or `ARGV.clear` go wrong... the user has bigger problems with her system than this one... :)

Anyways, squash to a single commit and I'll merge and release a new version with the fix. Thanks for your contribution @josephks !!

**Comment by josephks** [comment]
Squashed

**Pull request merged**
