### PR TITLE
Fix comments about catchpoints

### PR DESCRIPTION
**Pull request by yui-knk**

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
@yui-knk Thanks!

I have this setup in the repo that requires CI to pass before anything is merged to master (the merge button is disabled otherwise). Can you remove the [ci skip] part from the commit message and force-push?

**Comment by yui-knk** [comment]
🙇  Force pushed

**Comment by deivid-rodriguez** [comment]
Forgot to ask you to rebase too, sorry for getting you through all this trouble for a simple comment fix.

**Comment by yui-knk** [comment]
No problem 😄

**Comment by deivid-rodriguez** [comment]
Thanks a lot!!

**Pull request merged**
