### PR TITLE
No more monkey patching

### PR DESCRIPTION
**Pull request by os97673**
I've added some information debugger-xml needs from byebug to remove monkey-patching from debugger-xml.
I've made a small change in var.rb which will not allow us to remove monkey-patching completely because we do provide additional sub-commands and replace couple methods (see https://github.com/astashov/debugger-xml/blob/master/lib/byebug/commands/variables.rb)  Any ideas how to improve that is welcome.

Also debugger-xml monkey-patches several commands to make them "unsupported" (e.g. https://github.com/astashov/debugger-xml/blob/master/lib/byebug/commands/help.rb)
Again any ideas how to fix this w/o monkey-patching are welcome ;)

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
Thanks Oleg. I just added one inline comment.

Regarding removing monkeypatches. I've addressed the first issue with subcommands, I'll push the changes soon. I'm still thinking of the best way to support disabling commands. Maybe a whitelist of supported commands in the printer?

**Comment by os97673** [comment]
> I'll push the changes soon. I'm still thinking of the best way to support disabling commands. Maybe a whitelist of supported commands in the printer?

Well, I'd prefer to have some API in Byebug class for this.  E.g. modifiable list of commands or something similar.  Imho, printer is a wrong place for filtering commands.

**Comment by deivid-rodriguez** [comment]
Yep, I agree. But the idea of a whitelist works?

**Comment by os97673** [comment]
> But the idea of a whitelist works?

do you mean if it is ok to be able to whitelist/blacklist some commands?
If so, then yes, I think it is.

**Comment by deivid-rodriguez** [comment]
> do you mean if it is ok to be able to whitelist/blacklist some commands?
If so, then yes, I think it is.

Sorry I didn't answer this. Yes, I meant that plugins should provided a whitelist of the core byebug commands they want enabled.

I don't currently have time to work on this, just wanted to let you know in case you are waiting for me to move this forward.

Regards.

**Comment by os97673** [comment]
> Sorry I didn't answer this. Yes, I meant that plugins should provided a whitelist of the core byebug commands they want enabled.

Current approach debugger-xml uses is more like black-listing some commands most likely because most of commands you provide are useful for vim integration (for IDE we do not need to blacklist anything because user has not access to the debugger's commands ;)
Thus if/when you will have time for this I'd vote for blacklisting.

**Comment by deivid-rodriguez** [comment]
Got it, makes sense.

**Pull request merged**
