### PR TITLE
Adding missing require to processor files

### PR DESCRIPTION
**Pull request by guilherme**
As We discussed in: https://github.com/deivid-rodriguez/byebug/commit/da69f65a, adding some missing requires.

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
Thanks!

I know I'm very pick with style but, could you add a blank line after the require? I always leave a blank line between requires and the beginning of the code.

**Comment by guilherme** [comment]
Yeah, that's ok :+1: i've added it on: https://github.com/guilherme/byebug/commit/e425958d122d07ee9b5f4071dd382615c62a0433 

I'm not sure if it was the right approach, if you will squash it or i could do it here.

**Comment by deivid-rodriguez** [comment]
Yes, could you squash them?

**Comment by deivid-rodriguez** [comment]
Let me know If you need help with that.

**Comment by guilherme** [comment]
done :+1:

**Pull request merged**
