### PR TITLE
don't try to find a home dir byebugrc if there's no HOME

### LINKED ISSUE #270: Byebug fails with "no implicit conversion of nil into string"
With ruby 2.3.0, rails 5.0.0.beta3, rspec 3.5.0beta1, and byebug 9.0.4, putting a byebug invocation into a test fails.

```
$ bundle exec rspec -b

    <snip>

     Failure/Error: byebug

     TypeError:
       no implicit conversion of nil into String
     # /Users/llimllib/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/byebug-9.0.4/lib/byebug/core.rb:88:in `join'
     # /Users/llimllib/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/byebug-9.0.4/lib/byebug/core.rb:88:in `run_rc_file'
     # /Users/llimllib/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/byebug-9.0.4/lib/byebug/core.rb:50:in `run_init_script'
     # /Users/llimllib/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/byebug-9.0.4/lib/byebug/attacher.rb:16:in `attach'
     # /Users/llimllib/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/byebug-9.0.4/lib/byebug/attacher.rb:30:in `byebug'
     # ./app/controllers/ffm_controller.rb:111:in `get'
     # /Users/llimllib/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0.beta3/lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
     # /Users/llimllib/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0.beta3/lib/abstract_controller/base.rb:183:in `process_action'
     # /Users/llimllib/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0.beta3/lib/action_controller/metal/rendering.rb:30:in `process_action'
     # /Users/llimllib/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0.beta3/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
     # /Users/llimllib/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta3/lib/active_support/callbacks.rb:126:in `call'
     # /Users/llimllib/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta3/lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
     # /Users/llimllib/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta3/lib/active_support/callbacks.rb:455:in `call'
     # /Users/llimllib/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta3/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
     # /Users/llimllib/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta3/lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
     # /Users/llimllib/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta3/lib/active_support/callbacks.rb:90:in `run_callbacks'
     # /Users/llimllib/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0.beta3/lib/abstract_controller/callbacks.rb:19:in `process_action'
     # /Users/llimllib/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0.beta3/lib/action_controller/metal/rescue.rb:27:in `process_action'
     # /Users/llimllib/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0.beta3/lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
     # /Users/llimllib/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta3/lib/active_support/notifications.rb:164:in `block in instrument'
     # /Users/llimllib/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta3/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
     # /Users/llimllib/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta3/lib/active_support/notifications.rb:164:in `instrument'
     # /Users/llimllib/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0.beta3/lib/action_controller/metal/instrumentation.rb:29:in `process_action'
     # /Users/llimllib/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0.beta3/lib/action_controller/metal/params_wrapper.rb:248:in `process_action'
     # /Users/llimllib/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.beta3/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
     # /Users/llimllib/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0.beta3/lib/abstract_controller/base.rb:128:in `process'
     # /Users/llimllib/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionview-5.0.0.beta3/lib/action_view/rendering.rb:30:in `process'
     # /Users/llimllib/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0.beta3/lib/action_controller/metal.rb:190:in `dispatch'
     # /Users/llimllib/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0.beta3/lib/action_controller/test_case.rb:531:in `process'
     # /Users/llimllib/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0.beta3/lib/action_controller/test_case.rb:629:in `process_with_kwargs'
     # /Users/llimllib/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0.beta3/lib/action_controller/test_case.rb:381:in `get'
     # ./spec/controllers/ffm_controller_spec.rb:34:in `block (3 levels) in <top (required)>'
     # /Users/llimllib/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.0.beta1/lib/rspec/core/example.rb:236:in `instance_exec'
     # /Users/llimllib/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.0.beta1/lib/rspec/core/example.rb:236:in `block in run'
     # /Users/llimllib/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.0.beta1/lib/rspec/core/example.rb:478:in `block in with_around_and_singleton_context_hooks'
     # /Users/llimllib/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.0.beta1/lib/rspec/core/example.rb:435:in `block in with_around_example_hooks'
     # /Users/llimllib/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.0.beta1/lib/rspec/core/hooks.rb:478:in `block in run'
     # /Users/llimllib/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.0.beta1/lib/rspec/core/hooks.rb:618:in `block in run_around_example_hooks_for'
     # /Users/llimllib/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.0.beta1/lib/rspec/core/example.rb:320:in `call'
     # /Users/llimllib/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-rails-3.5.0.beta1/lib/rspec/rails/example/controller_example_group.rb:191:in `block (2 levels) in <module:ControllerExampleGroup>'
     # /Users/llimllib/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.0.beta1/lib/rspec/core/example.rb:425:in `instance_exec'
     # /Users/llimllib/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.0.beta1/lib/rspec/core/example.rb:425:in `instance_exec'
     # /Users/llimllib/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.0.beta1/lib/rspec/core/hooks.rb:389:in `execute_with'
     # /Users/llimllib/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.0.beta1/lib/rspec/core/hooks.rb:620:in `block (2 levels) in run_around_example_hooks_for'
     # /Users/llimllib/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.0.beta1/lib/rspec/core/example.rb:320:in `call'
     # /Users/llimllib/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-rails-3.5.0.beta1/lib/rspec/rails/adapters.rb:127:in `block (2 levels) in <module:MinitestLifecycleAdapter>'
     # /Users/llimllib/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.0.beta1/lib/rspec/core/example.rb:425:in `instance_exec'
     # /Users/llimllib/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.0.beta1/lib/rspec/core/example.rb:425:in `instance_exec'
     # /Users/llimllib/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.0.beta1/lib/rspec/core/hooks.rb:389:in `execute_with'
     # /Users/llimllib/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.0.beta1/lib/rspec/core/hooks.rb:620:in `block (2 levels) in run_around_example_hooks_for'
     # /Users/llimllib/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.0.beta1/lib/rspec/core/example.rb:320:in `call'
     # /Users/llimllib/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.0.beta1/lib/rspec/core/hooks.rb:621:in `run_around_example_hooks_for'
     # /Users/llimllib/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.0.beta1/lib/rspec/core/hooks.rb:478:in `run'
     # /Users/llimllib/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.0.beta1/lib/rspec/core/example.rb:435:in `with_around_example_hooks'
     # /Users/llimllib/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.0.beta1/lib/rspec/core/example.rb:478:in `with_around_and_singleton_context_hooks'
     # /Users/llimllib/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.0.beta1/lib/rspec/core/example.rb:233:in `run'
     # /Users/llimllib/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.0.beta1/lib/rspec/core/example_group.rb:595:in `block in run_examples'
     # /Users/llimllib/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.0.beta1/lib/rspec/core/example_group.rb:591:in `map'
     # /Users/llimllib/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.0.beta1/lib/rspec/core/example_group.rb:591:in `run_examples'
     # /Users/llimllib/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.0.beta1/lib/rspec/core/example_group.rb:557:in `run'
     # /Users/llimllib/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.0.beta1/lib/rspec/core/example_group.rb:558:in `block in run'
     # /Users/llimllib/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.0.beta1/lib/rspec/core/example_group.rb:558:in `map'
     # /Users/llimllib/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.0.beta1/lib/rspec/core/example_group.rb:558:in `run'
     # /Users/llimllib/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.0.beta1/lib/rspec/core/runner.rb:119:in `block (3 levels) in run_specs'
     # /Users/llimllib/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.0.beta1/lib/rspec/core/runner.rb:119:in `map'
     # /Users/llimllib/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.0.beta1/lib/rspec/core/runner.rb:119:in `block (2 levels) in run_specs'
     # /Users/llimllib/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.0.beta1/lib/rspec/core/configuration.rb:1680:in `with_suite_hooks'
     # /Users/llimllib/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.0.beta1/lib/rspec/core/runner.rb:118:in `block in run_specs'
     # /Users/llimllib/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.0.beta1/lib/rspec/core/reporter.rb:77:in `report'
     # /Users/llimllib/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.0.beta1/lib/rspec/core/runner.rb:117:in `run_specs'
     # /Users/llimllib/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.0.beta1/lib/rspec/core/runner.rb:93:in `run'
     # /Users/llimllib/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.0.beta1/lib/rspec/core/runner.rb:78:in `run'
     # /Users/llimllib/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.0.beta1/lib/rspec/core/runner.rb:45:in `invoke'
     # /Users/llimllib/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.0.beta1/exe/rspec:4:in `<top (required)>'
     # /Users/llimllib/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bin/rspec:23:in `load'
     # /Users/llimllib/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bin/rspec:23:in `<main>'
```

### PR DESCRIPTION
**Pull request by llimllib**
I looked briefly to see how to test it, but didn't see an obvious place to do it and am much too lazy.

I get four failing tests after this commit, just as I do in master.

fixes #270

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
Thanks!

I think this is the place for the test: https://github.com/deivid-rodriguez/byebug/blob/master/test/rc_test.rb

Also, could you use parenthesis for the `ENV.key?` call?

**Comment by llimllib** [comment]
Saw that file, but there aren't already calls to run_init_script and I'm not going to figure out how to use your test framework (sorry!)

**Comment by deivid-rodriguez** [comment]
No problem, thanks for the half baked patch! :)

I'll wrap it up when I have time.

**Comment by deivid-rodriguez** [comment]
Superseded by #272

**Pull request closed without merging**
