### PR TITLE
Fix travis caching

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
Also use the folder bundler 2 will use by default.

### CODE REVIEW

**Comment by MSP-Greg** [comment]
@deivid-rodriguez

Not sure if you noticed, looks like the 3 minute limit is no longer?

**Comment by deivid-rodriguez** [comment]
Sorry? I didn't understand the question.

**Comment by MSP-Greg** [comment]
I'm not sure what branch / PR is where, but looking at [Appveyor  history](https://ci.appveyor.com/project/deivid-rodriguez/byebug/history) shows the last build taking an hour?

Similar with Travis.

Sorry - Just noticed that the time PR hasn't been committed yet...

Greg

**Comment by deivid-rodriguez** [comment]
Ahh, yes. It should start working faster as soon as I merge it. (Travis will still be slow though due to macOS limited availability... :disappointed:)

**Pull request merged**
