### PR TITLE
Log .byebugrc errors to the console

### PR DESCRIPTION
**Pull request by sethk**
I notice there used to be a verbose option, which I think could be used to echo ``.byebugrc`` commands as they are executed. For now the verbose option of ``ScriptInterface`` doesn't seem to be connected to anything.

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
Thanks @sethk!

So before this, no output would be printed at all if we put, say, an invalid command inside `.byebugrc`? If that's the case, can we add a test for that?

**Comment by sethk** [comment]
Because of how `/dev/tty` works, I don't think there's a straightforward way to test for this. Something I thought about is passing `input`/`output`/`error` to the `Interface` initializer and nixing the `TestInterface` class. That way you could pass `StringIO`s to any of the interfaces for testing.

**Comment by deivid-rodriguez** [comment]
>  Something I thought about is passing input/output/error to the Interface initializer and nixing the TestInterface class. That way you could pass StringIOs to any of the interfaces for testing.

This is a very good idea. I wanted to do it for a long time but never got to it. Do you think you can get the ball rolling? Maybe not completely ditch the `TestInterface` class for now if it's too much work but figure this better dependency injection mechanism out so we can start testing these kind of things.

**Comment by deivid-rodriguez** [comment]
@sethk I did this myself in #267 without `IO.console`. We can think of adding that later. Can you have a look.

Closing in favor of #267

**Comment by deivid-rodriguez** [comment]
@sethk Just released 9.0.4 including this. Let me know!

**Comment by sethk** [comment]
Sorry for going AWOL. I will look into this and share some thoughts about refactoring soon.

**Comment by sethk** [comment]
Okay, now I can at least see the errors my startup script is generating. =)

**Pull request closed without merging**
