### PR TITLE
Fix break description.

### PR DESCRIPTION
**Pull request by x-yuri**
Not sure I understood the "add [#106](https://github.com/deivid-rodriguez/byebug/issues/106) to the help" part. And not sure if I came up with a good way to accomplish it.

### CODE REVIEW

**Comment by x-yuri** [comment]
@deivid-rodriguez Can you help with this failure?

```
  1) Failure:
Byebug::SteppingRescueTestCase#test_next_steps_over_rescue_when_raising_from_c_method [/home/yuri/_/byebug/test/commands/stepping_test.rb:144]:
--- expected
+++ actual
@@ -1 +1 @@
-9
+26
```

**Comment by x-yuri** [comment]
On second thought, that must be unrelated issue manifesting itself on that particular machine. Where I am now it doesn't fail.

**Comment by deivid-rodriguez** [comment]
Thanks @x-yuri, the PR was perfect!

The test failure was unrelated indeed, you're probably not using the latest patch level of Ruby on that machine. Upgrade and the test should pass.

**Comment by x-yuri** [comment]
I was running `ruby-2.1.2` there. In `ruby-2.1.3`, `ruby-2.1.4` and `ruby-2.1.5` the tests pass.

**Pull request merged**
