### PR TITLE
Fix creation of remote control processor

### PR DESCRIPTION
**Pull request by izaera**
Resend of previous pull request changing require_relative to require.

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
Thanks @izaera , I need you to rebase the PR so I can merge it.

**Comment by izaera** [comment]
Is that enough for merging @deivid-rodriguez? I'm not really sure what happened... I thought I had rebased locally before issuing the PR :-o

**Comment by deivid-rodriguez** [comment]
@izaera I like a linear PR rebased on top of master before merging it, so I'd like you to rework (or reopen) this PR to have a single commit. Regarding the build failure, I'm pretty sure it has nothing to do with this change.

**Comment by izaera** [comment]
OK. I have pushed -force the rebased commit. I finally discovered what happened: I was rebasing with origin/master instead of upstream/master :-( (that's because we don't use upstream right now at work).

**Comment by deivid-rodriguez** [comment]
> OK. I have pushed -force the rebased commit. 

Thanks @izaera ! :)

> I finally discovered what happened: I was rebasing with origin/master instead of upstream/master :-( (that's because we don't use upstream right now at work).

Yee, tha happens.

You're having very bad luck with this PR, lots of problems that are not your fault... Now the Appveyor build is failing... Could you try changing `gem install bundler` to `gem install bundler -v 1.11.2` in `appveyor.yml` in another commit and see if that fixes the build?

**Comment by deivid-rodriguez** [comment]
I added the workaround myself. You just need to rebase again.

**Comment by izaera** [comment]
There you go 👍

**Comment by deivid-rodriguez** [comment]
I'm so sorry for being a pain in the ass, but the current config of the repo is very strict... I still need another rebase for merging.

**Comment by izaera** [comment]
Done :-).

**Comment by deivid-rodriguez** [comment]
Thanks for your patience!

**Comment by izaera** [comment]
\o/

**Pull request merged**
