### PR TITLE
chore(travis): test against ruby 2.1.10

### PR DESCRIPTION
**Pull request by sanemat**
I cannot build byebug with Ruby 2.1.10.
~~I think this is `ffi` issue.~~
This is `rvm`'s or `travis-rubies`'s issue. https://github.com/travis-ci/travis-rubies/issues/15

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
Hi @sanemat ! Let's add the workaround you mention [here](https://github.com/travis-ci/travis-rubies/issues/15#issuecomment-207898200).

**Comment by sanemat** [comment]
I got it cf6236935da84660abc65ed25b41953f315cbbfe

**Comment by sanemat** [comment]
still fail 😢

**Comment by deivid-rodriguez** [comment]
@sanemat Apparently they've fixed this is travis and the workaround should no longer be necessary: https://github.com/travis-ci/travis-ci/issues/5862. Can you try again? Thank you!

**Comment by deivid-rodriguez** [comment]
Closed by #243

**Comment by sanemat** [comment]
thanks!

**Comment by deivid-rodriguez** [comment]
Thanks to you!

**Pull request closed without merging**
