### PR TITLE
Better runner and restart tests

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
## Description

Follow up to #324.

## Requirements

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][commits].
* [x] Used the same coding conventions as the rest of the project.
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [ ] All tests are passing.
* [x] The PR relates to *only* one subject.

[commits]: http://chris.beams.io/posts/git-commit

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
@MSP-Greg I'm having a similar problem here (subprocess hanging), I tried several versions of your fix but couldn't make it work... :disappointed:. I invited you as a collaborator to the repo so if you want to have a look, feel free to push directly to this branch :)

**Comment by MSP-Greg** [comment]
@deivid-rodriguez

> I invited you as a collaborator

Thank you, actually my first, as I tend to bounce around as a promoter of Windows/Appveyor/trunk testing.  I'll have a look a this (and remote) sometime soon.  You okay with finishing remote first?

**Comment by deivid-rodriguez** [comment]
@MSP-Greg Welcome, feel free to get involved as much as you want! :)

You already unblocked me in the other PR, I just want to add a little more coverage for the fixes it includes and it's good to go I think!

**Comment by deivid-rodriguez** [comment]
Closing in favor of #416 and (maybe) a separate PR to improve restart tests.

**Pull request closed without merging**
